### ISSUE TITLE
Dear author, could you please share the dataset? Thank you very much.

### ISSUE THREAD

**Issue by kekukin** [vasl12/SINR#1]

**Comment by vasl12** [comment]
Hi @kekukin,

The dataset I used is called CamCAN and you can request a license to access it via the webpage [https://cam-can.mrc-cbu.cam.ac.uk/](https://cam-can.mrc-cbu.cam.ac.uk/). I am afraid I do not have the permission to share the processed dataset I used.
Hope this helps.
